CREATE TABLE `external_orders` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `source` varchar(50) NOT NULL DEFAULT 'sopan',
  `event` varchar(255) DEFAULT NULL,
  `event_key` varchar(191) NOT NULL,
  `external_id` varchar(255) DEFAULT NULL,
  `shipment_id` varchar(255) DEFAULT NULL,
  `payment_status` varchar(255) DEFAULT NULL,
  `order_status` varchar(255) DEFAULT NULL,
  `fulfillment_type` varchar(255) DEFAULT NULL,
  `buyer_name` varchar(255) DEFAULT NULL,
  `buyer_email` varchar(255) DEFAULT NULL,
  `buyer_phone` varchar(255) DEFAULT NULL,
  `product_name` varchar(255) DEFAULT NULL,
  `package_name` varchar(255) DEFAULT NULL,
  `variant_id` varchar(255) DEFAULT NULL,
  `variant_sku` varchar(255) DEFAULT NULL,
  `variant_name` varchar(255) DEFAULT NULL,
  `duration_days` int unsigned DEFAULT NULL,
  `outlet_qty` int unsigned DEFAULT NULL,
  `entity_status` varchar(255) DEFAULT NULL,
  `entity_name` varchar(255) DEFAULT NULL,
  `item_qty` int unsigned DEFAULT NULL,
  `item_price` bigint unsigned DEFAULT NULL,
  `item_note` text DEFAULT NULL,
  `seller_note` text DEFAULT NULL,
  `subtotal_idr` bigint unsigned DEFAULT NULL,
  `shipping_cost_idr` bigint unsigned DEFAULT NULL,
  `total_idr` bigint unsigned DEFAULT NULL,
  `raw_payload` json DEFAULT NULL,
  `raw_headers` json DEFAULT NULL,
  `payload_keys` json DEFAULT NULL,
  `processing_status` varchar(255) NOT NULL DEFAULT 'received',
  `error_message` text DEFAULT NULL,
  `pricing_id` bigint unsigned DEFAULT NULL,
  `renewal_id` bigint unsigned DEFAULT NULL,
  `received_at` timestamp NULL DEFAULT NULL,
  `last_received_at` timestamp NULL DEFAULT NULL,
  `processed_at` timestamp NULL DEFAULT NULL,
  `duplicate_count` int unsigned NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `external_orders_event_key_unique` (`event_key`),
  KEY `external_orders_source_index` (`source`),
  KEY `external_orders_event_index` (`event`),
  KEY `external_orders_external_id_index` (`external_id`),
  KEY `external_orders_shipment_id_index` (`shipment_id`),
  KEY `external_orders_payment_status_index` (`payment_status`),
  KEY `external_orders_buyer_email_index` (`buyer_email`),
  KEY `external_orders_processing_status_index` (`processing_status`),
  KEY `external_orders_pricing_id_index` (`pricing_id`),
  KEY `external_orders_renewal_id_index` (`renewal_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
